customhost = "employee.cfk2gac6eesp.us-east-1.rds.amazonaws.com"
customuser = "vibhore"
custompass = "#Vibs0908"
customdb = "employee"
custombucket = "demowebapp-vibhore101"
customregion = "us-east-1"
